import PrimaryLayout from '@components/layouts/primary/primaryLayout';
import clsx from 'clsx';
import { Noto_Sans_Mono, Rubik } from 'next/font/google';
import './globals.css';

const noto = Noto_Sans_Mono({ subsets: ['latin'] });
const rubik = Rubik({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={clsx({ [noto.className]: true, [rubik.className]: true })}>
				<PrimaryLayout>
					{children}
				</PrimaryLayout>
			</body>
		</html>
	);
}
